# this script is for compiling all raw, individual absorbance csv's  
# into a single condensed absorbance csv table

# required input: individual absorbance csv files stored in one same folder
# expected output: a compiled absorbance csv (row = each sample, column = all different wavelengths)

# ALL FILE LOCATIONS ARE SUBJECT TO CHANGE



# load packages
library(plyr)
library(tidyverse)

# set working directory
working_directory1 <-  "D:\\RScripts\\proj_csvLoop_july15th2021\\UV1280_Data\\UV1280_cleaned_july14th15th2021\\CData_36Incubation"
working_directory2 <-  "D:\\RScripts\\proj_csvLoop_july15th2021\\UV1280_Data\\UV1280_cleaned_july14th15th2021\\CData_6export"
setwd(working_directory1)
getwd()


# create a function to read all csv files, skip the 1st row (due to raw data format generated by the UV machine),
# also add a new variable (column) named "filename"
read_plus <- function(flnm) {
  read_csv(flnm, skip = 1) %>% 
    mutate(filename = sub(".csv", "", flnm))}

# create a tbl with filenames
abs_data <- 
  list.files(pattern = "*.csv",
             full.names = FALSE) %>% 
  map_df(~read_plus(.))
View(abs_data)
str(abs_data)


# rename the "WL/nm" to "nm"
names(abs_data)[names(abs_data) == "WL/nm"] <- "nm"
View(abs_data)

# dcast data table long to wide
library(reshape2)
abs_cast<-dcast(abs_data, filename ~ nm,value.var = c("Abs"))
View(abs_cast)


# export the condensed csv
write.csv(abs_cast, "D:\\RScripts\\proj_csvLoop_july15th2021\\UV1280_Data\\UV1280_cleaned_july14th15th2021\\210715_Absorbance_Raw_36Incubation.csv")
#write.csv(abs_cast, "D:\\RScripts\\proj_csvLoop_july15th2021\\UV1280_Data\\UV1280_cleaned_july14th15th2021\\210715_Absorbance_Raw_6export.csv")

